#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : evince
Version  : 43.0
Release  : 67
URL      : https://download.gnome.org/sources/evince/43/evince-43.0.tar.xz
Source0  : https://download.gnome.org/sources/evince/43/evince-43.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-SA-3.0 GPL-2.0 MIT
BuildRequires : appstream
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gi-docgen
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(adwaita-icon-theme)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-pdf)
BuildRequires : pkgconfig(cairo-ps)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gi-docgen)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gmodule-no-export-2.0)
BuildRequires : pkgconfig(gnome-desktop-3.0)
BuildRequires : pkgconfig(gsettings-desktop-schemas)
BuildRequires : pkgconfig(gspell-1)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-base-1.0)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk+-unix-print-3.0)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libhandy-1)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(libspectre)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(poppler-glib)
BuildRequires : sed
BuildRequires : tiff-dev

%description
# ![evince-logo] Evince
Evince is a document viewer capable of displaying multiple and single
page document formats like PDF and Postscript.  For more general
information about Evince please visit our website at
https://wiki.gnome.org/Apps/Evince.

%prep
%setup -q -n evince-43.0
cd %{_builddir}/evince-43.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664892721
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dps=enabled \
-Dnautilus=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/evince
cp %{_builddir}/evince-%{version}/COPYING %{buildroot}/usr/share/package-licenses/evince/e3afbcad74dd08819b5de5ad0338203369731f67 || :
cp %{_builddir}/evince-%{version}/cut-n-paste/synctex/LICENSE %{buildroot}/usr/share/package-licenses/evince/024379152453bda1d28e9126d8685fa222c1174d || :
cp %{_builddir}/evince-%{version}/help/C/license.page %{buildroot}/usr/share/package-licenses/evince/99449fd3e6417f1f32dbe2a5b252880badb25704 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
